version: '3'

services:
  winestoreweb:
    image: winestoreweb
    build:
      context: ./WineStoreWeb
      dockerfile: Dockerfile

  winestoreapi:
    image: winestoreapi
    build:
      context: ./WineStoreApi
      dockerfile: Dockerfile

  winstoreinventory:
    image: winstoreinventory
    build:
      context: ./../WinStoreInventory
      dockerfile: Dockerfile
